databases:
  - name: servidorDeya
    plan: free
    databaseName: dbcine #no mayusculas
    user: deyaneira

services:
  - type: web
    plan: free
    name: cineUTC
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUTC.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorDeya
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutc-mb47.onrender.com


# set DATABASE_URL=postgresql://deyaneira:6VvgFccaHwHreI3Ql8ZVTKmrMasX6NN0@dpg-cqlpkkl6l47c73fj7hhg-a.oregon-postgres.render.com/dbcine_h2cg